[build]
  command = "mkdir -p out && cp landing-pageu47desktopu47v1u460.html out/index.html && cp -r css out/ && cp -r fonts out/ && cp -r img out/ && cp -r public/* out/"
  publish = "out"

# Custom headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
